apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      name: backend-feed
  template:
    metadata:
      labels:
        app: udagram
        name: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: phililab/udagram-api-feed@sha256:06ff0ea75ea08c303a49838bfd9137941f26789fbf82f7c26d734e3ec3796719
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret