apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      name: backend-user
  template:
    metadata:
      labels:
        app: udagram
        name: backend-user
    spec:
      containers:
        - name: backend-user
          image: phililab/udagram-api-user@sha256:91ce3bf95399f0c0fcff377af84bd600e56e083a347109116990a1fb734db154
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret