apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      service: backend-feed
      app: udagram
      name: backend-feed
  template:
    metadata:
      labels:
        app: udagram
        service: backend-feed
        name: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: phililab/udagram-api-feed@sha256:667e2dbb360eaca116fa9f48076747f406eb23f65e1efea58120c6d52339890f
          resources:
            requests:
              memory: "2000Mi"
              cpu: "250m"
            limits:
              memory: "2000Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret