apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      service: frontend
      name: frontend
  template:
    metadata:
      labels:
        app: udagram
        service: frontend
        name: frontend
    spec:
      containers:
        - name: frontend
          image: phililab/udagram-frontend@sha256:4f30e6e9716c3268584ea6f45780c54e3d3e3a537bc610c8e24a54ffd58a9c9f
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret