apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      service: frontend
      name: frontend
  template:
    metadata:
      labels:
        app: udagram
        service: frontend
        name: frontend
    spec:
      containers:
        - name: frontend
          image: phililab/udagram-frontend@sha256:24ede66185921cfc2a09c8f73e400d7b73232292a62e60e6099bd4592327f74d
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret