apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      name: reverseproxy
      service: reverseproxy
  template:
    metadata:
      labels:
        app: udagram
        name: reverseproxy
        service: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: phililab/reverseproxy@sha256:c094151737503336f4fc805165a3e85c4a16be0ccdd491be59fb3b9b47602546
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret