apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
      name: reverseproxy
  template:
    metadata:
      labels:
        app: udagram
        name: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: phililab/reverseproxy@sha256:e2fe99b5575b46397542d6186c197fe8d72ccdbce4de31b7bf170273a65124e1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secret
            - secretRef:
                name: aws-secret