apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  selector:
    app: udagram
    name: backend-user
    service: backend-user
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080