apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend-service
spec:
  selector:
    app: udagram
    name: frontend
    service: frontend
  ports:
    - name: "8100"
      port: 8100
      targetPort: 80