apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  selector:
    app: udagram
    name: reverseproxy
    service: reverseproxy
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080